'use strict';

module.exports = [
  '<phoneme alphabet="ipa" ph="saaaːlve">Salve</phoneme>',
  'a',
  '<phoneme alphabet="ipa" ph="tiiiiiˌː">ti</phoneme>,',
  '<phoneme alphabet="ipa" ph="ˌniiiiːkaɹ̆aaaaaˈː gʊa">Nicaragua</phoneme>',
  '<phoneme alphabet="ipa" ph="ˌeeeːn">en</phoneme>',
  'tu',
  '<phoneme alphabet="ipa" ph="sʊeeeeeeeeeˈː loˌ">suelo</phoneme> ',
  '<break time="450ms"/>',
  '<phoneme alphabet="ipa" ph="jaaaaaˈː">ya</phoneme>,',
  '<phoneme alphabet="ipa" ph="ɳooooː">no</phoneme>,',
  '<phoneme alphabet="ipa" ph="ruuuuuuː heeeeeˈː">ruge</phoneme>',
  'la',
  '<phoneme alphabet="ipa" ph="voooooːz">voz</phoneme>',
  '<phoneme alphabet="ipa" ph="deeeeˈˈːl">del</phoneme>',
  'cañon  ',
  '<break time="200ms"/>',
  '<phoneme alphabet="ipa" ph="niiiiˈː">ni</phoneme>',
  'se',
  '<phoneme alphabet="ipa" ph="tiiiiiːɲeeeː">tiñe</phoneme>',
  '<prosody rate="x-slow">con</prosody>',
  '<phoneme alphabet="ipa" ph="ˈˈsaaaaaaːngɹ̆eeeː">sangre</phoneme>',
  '<phoneme alphabet="ipa" ph="deeeːr maaaaaaˈˈː noooːs">de hermanos</phoneme> ',
  '<break time="100ms"/>',
  '<phoneme alphabet="ipa" ph="tuuuuˈˈː">tu</phoneme>',
  '<phoneme alphabet="ipa" ph="gloɹ̆ioooooː soooː">glorioso</phoneme>',
  '<phoneme alphabet="ipa" ph="peːnndoooː ˌoːn">pendon</phoneme>',
  '<phoneme alphabet="ipa" ph="ˈbiiiiːkooːloooooˈˈːr">bicolor</phoneme>',
  '<phoneme alphabet="ipa" ph="niiiiˈː">ni</phoneme>',
  'se ti',
  '<phoneme alphabet="ipa" ph="iiiː iɲeeeː">iñe</phoneme>',
  'con',
  '<phoneme alphabet="ipa" ph="ˈsaaaaaːn gɹ̆eee">sangre</phoneme>',
  '<phoneme alphabet="ipa" ph="deeeːr maaː nooːs">de hermanos</phoneme> ',
  '<phoneme alphabet="ipa" ph="tuuuˈˈː">tu</phoneme>',
  '<phoneme alphabet="ipa" ph="gloɹ̆ioooooː">glorio</phoneme>',
  '<phoneme alphabet="ipa" ph="soooː">so</phoneme>',
  '<phoneme alphabet="ipa" ph="peːnndoooː ˌoːn">pendon</phoneme>',
  '<phoneme alphabet="ipa" ph="ˈbiiiːkooːlooooˈˈːr">bicolor</phoneme>',
  '<break time="1500ms"/>',
  '<phoneme alphabet="ipa" ph="bɹ̆iiiːja">brilla</phoneme>',
  '<phoneme alphabet="ipa" ph="ˈˈermooooː saaaaː">hermosa</phoneme>',
  '<phoneme alphabet="ipa" ph="la paaaaaˈˈˈːz">la paz</phoneme>',
  '<phoneme alphabet="ipa" ph="eeeeːn">en</phoneme>',
  'tu',
  '<phoneme alphabet="ipa" ph="sieeeˈˈːlo">cielo</phoneme>',
  '<phoneme alphabet="ipa" ph="naaaaːdaˈˈ">nada</phoneme>',
  '<phoneme alphabet="ipa" ph="empaaaaaˈˈːɲeeeː tu">empañe tu</phoneme>',
  '<phoneme alphabet="ipa" ph="gloooooˈˈːɹia">gloria</phoneme>',
  '<phoneme alphabet="ipa" ph="inmooooːrtaːlˌ">inmortal</phoneme>',
  '<break time="300ms"/>',
  '<prosody rate="x-slow">',
  '    <phoneme alphabet="ipa" ph="keeːl">que el</phoneme>',
  '    <phoneme alphabet="ipa" ph="trabaaaːho eeeːs">trabajo es</phoneme>',
  '    <phoneme alphabet="ipa" ph="tu diiiː igno">tu digno</phoneme>',
  '    <phoneme alphabet="ipa" ph="laaːuɹ̆el">laurel</phoneme>,',
  '</prosody> ',
  '<phoneme alphabet="ipa" ph="iiː eeeːl onooooːr">y el honor</phoneme>',
  '<break time="680ms"/>',
  '<phoneme alphabet="ipa" ph="es tu enseeeːɲaaaː">es tu enseña</phoneme>',
  '<phoneme alphabet="ipa" ph="triunfaaaaːl">triunfal</phoneme>',
  '<break time="400ms"/>',
  '<phoneme alphabet="ipa" ph="eeeeːs">es</phoneme>',
  '<phoneme alphabet="ipa" ph="tuuuuː">tu</phoneme>',
  '<phoneme alphabet="ipa" ph="enseeeeː eɲaaaː">enseña</phoneme>',
  '<phoneme alphabet="ipa" ph="triunfaaaːl">triunfal</phoneme>',
];
