'use strict';

module.exports = [
  '<phoneme alphabet="ipa" ph="saaaːlve">Salve</phoneme>',
  'a',
  '<phoneme alphabet="ipa" ph="tiiiiiˌː">ti</phoneme>,',
  '<phoneme alphabet="ipa" ph="ˌniiiiːkaɹ̆aaaaː.gʊaaaˈː">Nicaragua</phoneme>,',
  '<phoneme alphabet="ipa" ph="eeeːn">en</phoneme>',
  'tu',
  '<phoneme alphabet="ipa" ph="sʊeeeeeeeeeˈː loˌ">suelo</phoneme> ',
  '<break time="500ms"/>',
  '<phoneme alphabet="ipa" ph="jaaaaaˈː">ya</phoneme>,',
  '<phoneme alphabet="ipa" ph="ɳooooː">no</phoneme>,',
  '<phoneme alphabet="ipa" ph="ruuuː">ruge</phoneme>,',
  '<phoneme alphabet="ipa" ph="heeeːlaː">la</phoneme>',
  '<phoneme alphabet="ipa" ph="vooooːz">voz</phoneme>',
  '<phoneme alphabet="ipa" ph="deeeeːl">del</phoneme>',
  'cañon ',
  '<break time="500ms"/>',
  '<phoneme alphabet="ipa" ph="niiiiˈː">ni</phoneme>',
  'se',
  '<phoneme alphabet="ipa" ph="tiiiiiːɲeeeː">tiñe</phoneme>',
  '<prosody rate="x-slow">con</prosody>',
  '<phoneme alphabet="ipa" ph="ˈˈsaaaaaaːngreː">sangre</phoneme>',
  '<phoneme alphabet="ipa" ph="deeːr maaaaaaˈˈˈː anos">hermanos</phoneme> ',
  '<break time="300ms"/>',
  '<phoneme alphabet="ipa" ph="tuuuˈˈː">tu</phoneme>',
  '<phoneme alphabet="ipa" ph="gloɹ̆iooooːsooo">glorioso</phoneme>',
  '<phoneme alphabet="ipa" ph="pendoooːn">pendon</phoneme>,',
  '<phoneme alphabet="ipa" ph="ˈˈbiiiːkolooooːr">bicolor</phoneme>',
  '<break time="300ms"/>',
  '<phoneme alphabet="ipa" ph="niiiiˈː">ni</phoneme>',
  'se',
  '<phoneme alphabet="ipa" ph="tiiiiiːɲeeeː">tiñe</phoneme>',
  '<prosody rate="x-slow">con</prosody>',
  '<phoneme alphabet="ipa" ph="ˈˈsaaaaaaːngreː">sangre</phoneme>',
  '<phoneme alphabet="ipa" ph="deeːr maaaaaaˈˈˈː anos">hermanos</phoneme> ',
  '<break time="300ms"/>',
  '<phoneme alphabet="ipa" ph="tuuuˈˈː">tu</phoneme>',
  '<phoneme alphabet="ipa" ph="gloɹ̆iooooːsooo">glorioso</phoneme>',
  '<phoneme alphabet="ipa" ph="pendoooːn">pendon</phoneme>,',
  '<phoneme alphabet="ipa" ph="ˈˈbiiiːkolooooːr">bicolor</phoneme>',
  '<break time="1s"/>',
  '<phoneme alphabet="ipa" ph="bɹ̆iiiːja">brilla</phoneme>',
  '<phoneme alphabet="ipa" ph="ˈˈermooooː saaaaː">hermosa</phoneme>',
  '<phoneme alphabet="ipa" ph="la paaaaaˈˈˈːz">la paz</phoneme>',
  '<break time="100ms"/>',
  '<phoneme alphabet="ipa" ph="eeeeeːn">ni</phoneme>',
  '<prosody rate="x-slow">tu</prosody>',
  '<prosody rate="slow">',
  '    <phoneme alphabet="ipa" ph="sieeeˈˈːlo">cielo</phoneme>',
  '    <phoneme alphabet="ipa" ph="naaaːdaˈˈ">nada</phoneme>',
  '    <phoneme alphabet="ipa" ph="empaaaaˈˈːɲeeeːn tu">tine</phoneme>',
  '    <phoneme alphabet="ipa" ph="gloooooˈˈːɹia">gloria</phoneme>',
  '    <phoneme alphabet="ipa" ph="inmooːrtalˌ">inmortal</phoneme>',
  '</prosody> ',
  '<break time="300ms"/>',
  '<prosody rate="x-slow">',
  '    <phoneme alphabet="ipa" ph="keeːl">que el</phoneme>',
  '    <phoneme alphabet="ipa" ph="trabaaaːho es">trabajo es</phoneme>,',
  '    <phoneme alphabet="ipa" ph="tu diiiː igno">tu digno</phoneme>',
  '    <phoneme alphabet="ipa" ph="laːuɹ̆el">laurel</phoneme>',
  '</prosody> ',
  '<break time="200ms"/>',
  '<phoneme alphabet="ipa" ph="iiː eeeːl onooooːr">y el honor</phoneme>',
  '<break time="200ms"/>',
  '<phoneme alphabet="ipa" ph="es tu enseeeːɲaaaː">es tu enseña</phoneme>',
  '<phoneme alphabet="ipa" ph="triunfaaaːl">triunfal</phoneme>',
  '<break time="200ms"/>',
  '<phoneme alphabet="ipa" ph="eeeeːs">es</phoneme>',
  '<phoneme alphabet="ipa" ph="tuuuː">tu</phoneme>',
  '<phoneme alphabet="ipa" ph="enseeeː eɲaaaː">ensenha</phoneme>',
  '<phoneme alphabet="ipa" ph="triunfaaaːl">triunfal</phoneme>',
];
